language: node_js
script: node_modules/karma/bin/karma start test-config/karma.conf.js --single-run
before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_script:
    - npm install